# Generated by Django 2.1.4 on 2018-12-20 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='game day')),
                ('ppg', models.IntegerField()),
                ('apg', models.IntegerField()),
                ('rpg', models.IntegerField()),
                ('tpg', models.IntegerField()),
                ('gmscre', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=200)),
                ('player_team', models.CharField(max_length=200)),
                ('ppg', models.IntegerField()),
                ('apg', models.IntegerField()),
                ('rpg', models.IntegerField()),
                ('tpg', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mvp.Player'),
        ),
    ]
