# Generated by Django 2.1.4 on 2018-12-25 06:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 25, 6, 58, 14, 287386, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='player',
            name='apg',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='ascore',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='ppg',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='rpg',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='tpg',
            field=models.FloatField(),
        ),
    ]
