# Generated by Django 2.1.4 on 2018-12-21 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='apg',
            new_name='assists',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='ppg',
            new_name='points',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='rpg',
            new_name='rebounds',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='tpg',
            new_name='turnovers',
        ),
    ]
