# Generated by Django 2.1.4 on 2018-12-22 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0002_auto_20181221_0628'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='ascore',
            field=models.IntegerField(default=0),
        ),
    ]
