# Generated by Django 2.1.4 on 2019-01-09 06:01

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0003_auto_20181225_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 9, 6, 1, 13, 959126, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='game',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player', to='mvp.Player'),
        ),
        migrations.AlterField(
            model_name='player',
            name='apg',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='ppg',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='rpg',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='tpg',
            field=models.FloatField(default=0),
        ),
    ]
