# Generated by Django 2.1.4 on 2019-01-09 06:47

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0004_auto_20190109_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 9, 6, 47, 5, 237678, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='game',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mvp.Player'),
        ),
    ]
