# Generated by Django 2.1.4 on 2019-01-09 20:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0006_auto_20190109_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 9, 20, 0, 4, 813492, tzinfo=utc)),
        ),
    ]
