# Generated by Django 2.1.4 on 2019-01-09 20:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0008_auto_20190109_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 9, 20, 3, 45, 466041, tzinfo=utc)),
        ),
    ]
